### ISSUE TITLE
Idée de gestion des chaines 

### ISSUE THREAD

**Issue by Che-debarras** [Sphinxroot/M3U-URL#1]
> jai quelque liste sur mon git si ca peut interresser ;)

Les chaines belgiques (la une la deux la trois ne marchent pas) 
Il y a aps non plus RTS1 RTS2 RTS3 de la suisse
Il manque quelque chaines française 

@Sphinxroot merci , si tu pouvez faire une liste special francophone (belgique France suisse  algerie maroc tunisie + quebec) car les chaines internationales des différents pays c'est dure à gerer sur perfect player.

**Comment by Sphinxroot** [comment]
pour avoir une liste complete y a qua les fusionners avant instalation  ou te cree un fichier index avec tout les urls vers les fichiers m3u

 geolocalisation   pour RTI  " Ce contenu n'est accessible que depuis la Suisse et ne peut donc être joué. " alors vpn pour plusieur 
tout comme la liste quebec beaucoup aurrons la geoblock  pour l outremer

et belgique  la une .. fonctionne pour moi , la 2 et la 3 pas toujours ...

pour le contenu franco autre que l europe https://raw.githubusercontent.com/Sphinxroot/M3U-URL/master/francais%20monde.m3u

certe tout les caneaux n y sont pas pour cause " Geo (Vpn) , Expirable , DMR , Sequentiel , ou non supporter par kodi (demuxer)

l`astuce disponiple est d utiliser firefox avec le plugin cast to kodi https://addons.mozilla.org/en-US/firefox/addon/castkodi/ via n importe quel appareil voir la configuration requise ce qui permets de difuser n importe quel lien sur kodi  en reseau local

:)
