### ISSUE TITLE
CBC News Network link hasn't worked in about 1 month

### ISSUE THREAD

**Issue by whoisearth** [Sphinxroot/M3U-URL#3]
#EXTINF:-1 tvg-logo="https://i.imgur.com/SGbZKbJ.png" group-title="News",CBC New Network
https://livecbcdai-i.akamaihd.net/hls/live/567245/event2/CBCNN/master6.m3u8

**Comment by Sphinxroot** [comment]
thanks for reporting  .. now fixed they removed the 1080 link now only in 720  :)
